julia Main.jl -n 1
julia Main.jl -n 2
julia Main.jl -n 3
julia Main.jl -n 4
julia Main.jl -n 5
julia Main.jl -n 6
julia Main.jl -n 7
julia Main.jl -n 8
julia Main.jl -n 9
julia Main.jl -n 10
julia Main.jl -n 11
julia Main.jl -n 12
julia Main.jl -n 13
julia Main.jl -n 14
julia Main.jl -n 15
julia Main.jl -n 16
julia Main.jl -n 17
julia Main.jl -n 18
julia Main.jl -n 19
julia Main.jl -n 20
julia Main.jl -n 21
julia Main.jl -n 22
julia Main.jl -n 23
julia Main.jl -n 24
julia Main.jl -n 25
julia Main.jl -n 26
julia Main.jl -n 27
julia Main.jl -n 28
julia Main.jl -n 29
julia Main.jl -n 30
julia Main.jl -n 31
julia Main.jl -n 32
julia Main.jl -n 33
julia Main.jl -n 34
julia Main.jl -n 35
julia Main.jl -n 36
julia Main.jl -n 37
julia Main.jl -n 38
julia Main.jl -n 39
julia Main.jl -n 40
julia Main.jl -n 41
julia Main.jl -n 42
julia Main.jl -n 43
julia Main.jl -n 44
julia Main.jl -n 45
julia Main.jl -n 46
julia Main.jl -n 47
julia Main.jl -n 48
julia Main.jl -n 49
julia Main.jl -n 50
julia Main.jl -n 51
julia Main.jl -n 52
julia Main.jl -n 53
julia Main.jl -n 54
julia Main.jl -n 55
julia Main.jl -n 56
julia Main.jl -n 57
julia Main.jl -n 58
julia Main.jl -n 59
julia Main.jl -n 60
julia Main.jl -n 61
julia Main.jl -n 62
julia Main.jl -n 63
julia Main.jl -n 64
julia Main.jl -n 65
julia Main.jl -n 66
julia Main.jl -n 67
julia Main.jl -n 68
julia Main.jl -n 69
julia Main.jl -n 70
julia Main.jl -n 71
julia Main.jl -n 72
julia Main.jl -n 73
julia Main.jl -n 74
julia Main.jl -n 75
julia Main.jl -n 76
julia Main.jl -n 77
julia Main.jl -n 78
julia Main.jl -n 79
julia Main.jl -n 80
julia Main.jl -n 81
julia Main.jl -n 82
julia Main.jl -n 83
julia Main.jl -n 84
julia Main.jl -n 85
julia Main.jl -n 86
julia Main.jl -n 87
julia Main.jl -n 88
julia Main.jl -n 89
julia Main.jl -n 90
julia Main.jl -n 91
julia Main.jl -n 92
julia Main.jl -n 93
julia Main.jl -n 94
julia Main.jl -n 95
julia Main.jl -n 96
julia Main.jl -n 97
julia Main.jl -n 98
julia Main.jl -n 99
julia Main.jl -n 100